version: "3"
services:
  core2:
    image: "docker-core:dev"
    ports:
      - "1260:1260"
      - "1261:1261"
      - "1262:1262"
      - "1263:1263"
      - "1264:1264"
      - "5702:5702"
    environment:
      - HOST=127.0.0.1
      - BACKEND_PORT=1260
      - CONTROL_PUB_PORT=1261
      - CONTROL_SUB_PORT=1262
      - DATA_PUB_PORT=1263
      - DATA_SUB_PORT=1264

      - BACKEND_HOST=core2
      - HAZELCAST_PORT=5702
